#!/usr/bin/env node
'use strict';

const fs = require('node:fs/promises');
const path = require('node:path');
const { buildVariant, LOCAL_OUTPUT, PUBLIC_OUTPUT } = require('./build-site.cjs');

async function main() {
  const apply = process.argv.slice(2).includes('--apply');
  const outputs = [
    { mode: 'local', destination: LOCAL_OUTPUT },
    { mode: 'public', destination: PUBLIC_OUTPUT },
  ];
  let mismatch = false;
  for (const item of outputs) {
    const { output } = await buildVariant(item.mode);
    const current = await fs.readFile(item.destination, 'utf8').catch(() => null);
    const changed = current !== output;
    if (changed) mismatch = true;
    if (apply && changed) {
      await fs.mkdir(path.dirname(item.destination), { recursive: true });
      await fs.writeFile(item.destination, output, 'utf8');
    }
    const label = apply ? (changed ? 'WROTE' : 'CURRENT') : (changed ? 'STALE' : 'CURRENT');
    process.stdout.write(`${label} ${path.relative(__dirname, item.destination)} (${Buffer.byteLength(output)} generated bytes)\n`);
  }
  if (!apply && mismatch) {
    process.stderr.write('Generated site outputs differ from canonical source. Run npm run sync:site to apply the build.\n');
    process.exitCode = 1;
  } else if (!apply) {
    process.stdout.write('Generated local and deployment outputs match the canonical source.\n');
  }
}

main().catch(error => { console.error(error.stack || error); process.exitCode = 1; });
