// V9.6 browser checks: draft persistence, work transfer, validation and dismissible conflicts.
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { pathToFileURL } = require('node:url');
const { chromium } = require('playwright');
(async () => {
    const browser = await chromium.launch({ channel: 'chrome', headless: true });
    try {
        const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
        const errors = [];
        page.on('pageerror', e => errors.push(e.message));
        let accept = true;
        page.on('dialog', dialog => accept ? dialog.accept() : dialog.dismiss());
        const url = pathToFileURL(path.join(__dirname, 'Prompts Builder V9.6.html')).href;
        await page.goto(url);
        const subject = page.getByPlaceholder('描述畫面的核心主體...');
        await subject.waitFor({ timeout: 60000 });
        await subject.fill('恢復測試 🐈');
        await page.locator('#section-params summary').click();
        await page.locator('#text-language').selectOption('custom');
        await page.locator('#language-prompt').fill('繁中、English、日本語');
        await page.waitForFunction(() => JSON.parse(localStorage.getItem('prompt_builder_draft_v1') || '{}').languagePromptOverrides?.custom === '繁中、English、日本語');
        const original = await page.evaluate(() => JSON.parse(localStorage.getItem('prompt_builder_draft_v1')));
        await page.reload();
        await subject.waitFor();
        assert.equal(await subject.inputValue(), original.form.subject);
        assert.match(await page.getByTestId('draft-status').innerText(), /恢復/);
        const downloadEvent = page.waitForEvent('download');
        await page.getByRole('button', { name: '匯出作品', exact: true }).click();
        const download = await downloadEvent;
        const exported = JSON.parse(fs.readFileSync(await download.path(), 'utf8'));
        assert.deepEqual(exported, original);
        const file = data => ({ name: 'work.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify(data)) });
        await subject.fill('新內容');
        accept = false;
        await page.getByTestId('work-import').setInputFiles(file(exported));
        await page.waitForTimeout(100);
        assert.equal(await subject.inputValue(), '新內容', 'cancel preserves work');
        accept = true;
        await page.getByTestId('work-import').setInputFiles(file(exported));
        await page.waitForFunction(() => document.querySelector('#section-global input').value === '恢復測試 🐈');
        await page.locator('#section-params summary').click();
        assert.equal(await page.locator('#language-prompt').inputValue(), '繁中、English、日本語');
        for (const bad of [{}, { ...exported, schemaVersion: 999 }, { ...exported, textLanguage: 'invalid' }, { ...exported, form: { ...exported.form, sections: [null] } }]) {
            await page.getByTestId('work-import').setInputFiles(file(bad));
            await page.getByText(/匯入失敗：/).waitFor();
            assert.equal(await subject.inputValue(), original.form.subject);
        }
        const conflict = structuredClone(exported);
        conflict.form.selectedStyles = ['Photorealistic', 'Flat Design'];
        conflict.form.sections = [{ visual: 'scene', param: 'Left', dir: 'row', textBlocks: [{ content: '內容', level: 'Primary', font: 'Noto Sans TC', weight: 'Bold' }] }];
        await page.getByTestId('work-import').setInputFiles(file(conflict));
        const warnings = page.getByRole('complementary', { name: '提示詞衝突提醒' });
        await warnings.waitFor();
        await warnings.getByRole('button', { name: '忽略此提醒' }).click();
        assert.equal(await warnings.count(), 0);
        await page.getByRole('button', { name: '重新顯示衝突提醒' }).click();
        assert(await warnings.isVisible());
        const pedi = structuredClone(conflict);
        pedi.form.selectedStyles = ['minimal modern medical illustration', 'soft watercolor illustration on pale paper'];
        await page.getByTestId('work-import').setInputFiles(file(pedi));
        await page.getByText(/無字風格與文字內容並存/).waitFor();
        assert(await page.getByText(/選了多個衛教風格/).isVisible());
        await page.waitForFunction(() => JSON.parse(localStorage.getItem('prompt_builder_draft_v1')).form.selectedStyles.includes('minimal modern medical illustration'));
        assert.deepEqual(await page.evaluate(() => JSON.parse(localStorage.getItem('prompt_builder_draft_v1')).form.sections), pedi.form.sections);
        await page.addInitScript(() => localStorage.setItem('prompt_builder_draft_v1', '{broken'));
        await page.reload();
        await subject.waitFor();
        assert.match(await page.getByTestId('draft-status').innerText(), /失敗/);
        assert.equal(await page.evaluate(() => localStorage.getItem('prompt_builder_draft_v1')), '{broken');
        await page.evaluate(() => { const original = Storage.prototype.setItem; Storage.prototype.setItem = function(k, v) { if (k === 'prompt_builder_draft_v1') throw new Error('quota'); return original.call(this, k, v); }; });
        await subject.fill('storage error test');
        await page.waitForTimeout(600);
        assert.match(await page.getByTestId('draft-status').innerText(), /失敗/);
        assert.deepEqual(errors, []);
        console.log('PASS V9.6: draft reload, Unicode/multilingual export/import, cancel, invalid schema, full sections, all conflict rules, dismiss/restore, corrupt draft and storage failure.');
    } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
